### ISSUE TITLE
公共模板无法访问，上传其他har文件无法签到，麻烦大佬了

### ISSUE THREAD

**Issue by ZHOU202** [AragonSnow/qiandao#29]
![QQ截图20201011225625](https://user-images.githubusercontent.com/40857974/95681938-28020680-0c15-11eb-89df-586fbca561e9.jpg)
大佬重新拉取你的镜像，创建成功了，但是有新问题

**Comment by AragonSnow** [comment]
@ZHOU202 
。。。你拉的也不是我的镜像呀
至于为什么失败，你先运行docker logs qiandao2我看看日志先

**Comment by ZHOU202** [comment]
大佬，重新拉取了你的镜像，有两个问题，
1、公共模板需要科学上网打开全局才能正常访问，其他情况下就会出现以下代码
签到失败
HTTPSConnectionPool(host='gitee.com', port=443): Max retries exceeded with url: /api/v5/repos/qiandao-today/templates/readme (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff8c449090>: Failed to establish a new connection: [Errno 111] Connection refused',))
2、上传自己搭建的har文件进行签到，也需要打开全局科学上网才能正常签到，蜜汁不解，还望大佬解答
![QQ截图20201015173138](https://user-images.githubusercontent.com/40857974/96105379-8a585100-0f0c-11eb-8737-fc47f0f9ed2d.jpg)
![QQ截图20201015173311](https://user-images.githubusercontent.com/40857974/96105397-8f1d0500-0f0c-11eb-92da-3c5a1585ae73.jpg)

**Comment by ZHOU202** [comment]
> @ZHOU202
> 。。。你拉的也不是我的镜像呀
> 至于为什么失败，你先运行docker logs qiandao2我看看日志先
大佬，拉取你的镜像之后，这是日志
stdout: [E 201015 00:00:02 worker:274] taskid:3 tplid:3 failed! Exception(u"failed at 1/11 request, error:error(111, 'Connection refused'), https://api.smzdm.com/v1/user/checkin",) 0.2609s
stderr: [E 201015 00:00:02 worker:274] taskid:3 tplid:3 failed! Exception(u"failed at 1/11 request, error:error(111, 'Connection refused'), https://api.smzdm.com/v1/user/checkin",) 0.2609s
stdout: [E 201015 00:00:03 worker:274] taskid:2 tplid:2 failed! Exception(u"failed at 1/1 request, error:error(111, 'Connection refused'), https://www.right.com.cn/forum/forum.php",) 0.6069s
stderr: [E 201015 00:00:03 worker:274] taskid:2 tplid:2 failed! Exception(u"failed at 1/1 request, error:error(111, 'Connection refused'), https://www.right.com.cn/forum/forum.php",) 0.6069s
stdout: [I 201015 00:00:03 worker:51] 2 task done. 0 success, 2 failed
stdout: [I 201015 00:00:13 worker:216] taskid:1 tplid:1 successed! 0.7100s
stdout: [I 201015 00:00:13 worker:51] 1 task done. 1 success, 0 failed
stderr: [E 201015 00:10:12 worker:274] taskid:3 tplid:3 failed! Exception(u"failed at 1/11 request, error:error(111, 'Connection refused'), https://api.smzdm.com/v1/user/checkin",) 0.1959s
stdout: [E 201015 00:10:12 worker:274] taskid:3 tplid:3 failed! Exception(u"failed at 1/11 request, error:error(111, 'Connection refused'), https://api.smzdm.com/v1/user/checkin",) 0.1959s
stdout: [E 201015 00:10:12 worker:274] taskid:2 tplid:2 failed! Exception(u"failed at 1/1 request, error:error(111, 'Connection refused'), https://www.right.com.cn/forum/forum.php",) 0.5178s
stderr: [E 201015 00:10:12 worker:274] taskid:2 tplid:2 failed! Exception(u"failed at 1/1 request, error:error(111, 'Connection refused'), https://www.right.com.cn/forum/forum.php",) 0.5178s
stdout: [I 201015 00:10:12 worker:51] 2 task done. 0 success, 2 failed
stdout: [E 201015 02:00:22 worker:274] taskid:3 tplid:3 failed! Exception(u"failed at 1/11 request, error:error(111, 'Connection refused'), https://api.smzdm.com/v1/user/checkin",) 0.2247s
stderr: [E 201015 02:00:22 worker:274] taskid:3 tplid:3 failed! Exception(u"failed at 1/11 request, error:error(111, 'Connection refused'), https://api.smzdm.com/v1/user/checkin",) 0.2247s
stdout: [E 201015 02:00:23 worker:274] taskid:2 tplid:2 failed! Exception(u"failed at 1/1 request, error:error(111, 'Connection refused'), https://www.right.com.cn/forum/forum.php",) 0.5474s
stderr: [E 201015 02:00:23 worker:274] taskid:2 tplid:2 failed! Exception(u"failed at 1/1 request, error:error(111, 'Connection refused'), https://www.right.com.cn/forum/forum.php",) 0.5474s
stdout: [I 201015 02:00:23 worker:51] 2 task done. 0 success, 2 failed
stdout: [E 201015 06:00:34 worker:274] taskid:3 tplid:3 failed! Exception(u"failed at 1/11 request, error:error(111, 'Connection refused'), https://api.smzdm.com/v1/user/checkin",) 0.8373s
stderr: [E 201015 06:00:34 worker:274] taskid:3 tplid:3 failed! Exception(u"failed at 1/11 request, error:error(111, 'Connection refused'), https://api.smzdm.com/v1/user/checkin",) 0.8373s
stdout: [E 201015 06:00:34 worker:274] taskid:2 tplid:2 failed! Exception(u"failed at 1/1 request, error:error(111, 'Connection refused'), https://www.right.com.cn/forum/forum.php",) 1.7470s
stderr: [E 201015 06:00:34 worker:274] taskid:2 tplid:2 failed! Exception(u"failed at 1/1 request, error:error(111, 'Connection refused'), https://www.right.com.cn/forum/forum.php",) 1.7470s
stdout: [I 201015 06:00:34 worker:51] 2 task done. 0 success, 2 failed
stderr: [E 201015 12:00:42 worker:274] taskid:3 tplid:3 failed! Exception(u"failed at 1/11 request, error:error(111, 'Connection refused'), https://api.smzdm.com/v1/user/checkin",) 0.1971s
stdout: [E 201015 12:00:42 worker:274] taskid:3 tplid:3 failed! Exception(u"failed at 1/11 request, error:error(111, 'Connection refused'), https://api.smzdm.com/v1/user/checkin",) 0.1971s
stdout: [E 201015 12:00:42 worker:274] taskid:2 tplid:2 failed! Exception(u"failed at 1/1 request, error:error(111, 'Connection refused'), https://www.right.com.cn/forum/forum.php",) 0.4883s
stderr: [E 201015 12:00:42 worker:274] taskid:2 tplid:2 failed! Exception(u"failed at 1/1 request, error:error(111, 'Connection refused'), https://www.right.com.cn/forum/forum.php",) 0.4883s
stdout: [I 201015 12:00:42 worker:51] 2 task done. 0 success, 2 failed
stdout: [I 201015 17:23:13 web:2064] 302 GET / (172.31.0.1) 30.47ms
stdout: [I 201015 17:23:14 web:2064] 200 GET /my/ (172.31.0.1) 72.03ms
stdout: [I 201015 17:23:15 web:2064] 304 GET /static/body.jpg (172.31.0.1) 4.60ms
stdout: [I 201015 17:23:15 web:2064] 304 GET /static/header.jpg (172.31.0.1) 3.94ms
stdout: [I 201015 17:23:15 web:2064] 304 GET /static/components/bootstrap/dist/fonts/glyphicons-halflings-regular.woff (172.31.0.1) 4.20ms
stdout: [I 201015 17:23:16 web:2064] 200 GET /static/img/icon.png?v=805c611920555b870651cd98c6f93777 (172.31.0.1) 6.35ms
stdout: [I 201015 17:23:46 web:2064] 200 GET /subscribe/ (172.31.0.1) 116.46ms
stdout: [W 201015 17:23:47 web:2064] 404 GET /favicon.ico (172.31.0.1) 11.88ms
stderr: [W 201015 17:23:47 web:2064] 404 GET /favicon.ico (172.31.0.1) 11.88ms
stdout: [I 201015 17:30:46 web:2064] 200 GET /subscribe/ (172.31.0.1) 84.89ms
stdout: [I 201015 17:33:00 web:2064] 304 GET /my/ (172.31.0.1) 34.83ms
stdout: [I 201015 17:36:18 web:2064] 302 GET / (172.31.0.1) 5.87ms
stdout: [I 201015 17:36:18 web:2064] 304 GET /my/ (172.31.0.1) 39.49ms
stdout: [I 201015 17:36:22 web:2064] 200 POST /task/3/run (172.31.0.1) 192.42ms
stdout: [I 201015 17:36:25 web:2064] 200 POST /task/2/run (172.31.0.1) 203.14ms

**Comment by ZHOU202** [comment]
stdout: [E 201015 00:00:02 worker:274] taskid:3 tplid:3 failed! Exception(u"failed at 1/11 request, error:error(111, 'Connection refused'), https://api.smzdm.com/v1/user/checkin",) 0.2609s
stderr: [E 201015 00:00:02 worker:274] taskid:3 tplid:3 failed! Exception(u"failed at 1/11 request, error:error(111, 'Connection refused'), https://api.smzdm.com/v1/user/checkin",) 0.2609s
stdout: [E 201015 00:00:03 worker:274] taskid:2 tplid:2 failed! Exception(u"failed at 1/1 request, error:error(111, 'Connection refused'), https://www.right.com.cn/forum/forum.php",) 0.6069s
stderr: [E 201015 00:00:03 worker:274] taskid:2 tplid:2 failed! Exception(u"failed at 1/1 request, error:error(111, 'Connection refused'), https://www.right.com.cn/forum/forum.php",) 0.6069s
stdout: [I 201015 00:00:03 worker:51] 2 task done. 0 success, 2 failed
stdout: [I 201015 00:00:13 worker:216] taskid:1 tplid:1 successed! 0.7100s
stdout: [I 201015 00:00:13 worker:51] 1 task done. 1 success, 0 failed
stderr: [E 201015 00:10:12 worker:274] taskid:3 tplid:3 failed! Exception(u"failed at 1/11 request, error:error(111, 'Connection refused'), https://api.smzdm.com/v1/user/checkin",) 0.1959s
stdout: [E 201015 00:10:12 worker:274] taskid:3 tplid:3 failed! Exception(u"failed at 1/11 request, error:error(111, 'Connection refused'), https://api.smzdm.com/v1/user/checkin",) 0.1959s
stdout: [E 201015 00:10:12 worker:274] taskid:2 tplid:2 failed! Exception(u"failed at 1/1 request, error:error(111, 'Connection refused'), https://www.right.com.cn/forum/forum.php",) 0.5178s
stderr: [E 201015 00:10:12 worker:274] taskid:2 tplid:2 failed! Exception(u"failed at 1/1 request, error:error(111, 'Connection refused'), https://www.right.com.cn/forum/forum.php",) 0.5178s
stdout: [I 201015 00:10:12 worker:51] 2 task done. 0 success, 2 failed
stdout: [E 201015 02:00:22 worker:274] taskid:3 tplid:3 failed! Exception(u"failed at 1/11 request, error:error(111, 'Connection refused'), https://api.smzdm.com/v1/user/checkin",) 0.2247s
stderr: [E 201015 02:00:22 worker:274] taskid:3 tplid:3 failed! Exception(u"failed at 1/11 request, error:error(111, 'Connection refused'), https://api.smzdm.com/v1/user/checkin",) 0.2247s
stdout: [E 201015 02:00:23 worker:274] taskid:2 tplid:2 failed! Exception(u"failed at 1/1 request, error:error(111, 'Connection refused'), https://www.right.com.cn/forum/forum.php",) 0.5474s
stderr: [E 201015 02:00:23 worker:274] taskid:2 tplid:2 failed! Exception(u"failed at 1/1 request, error:error(111, 'Connection refused'), https://www.right.com.cn/forum/forum.php",) 0.5474s
stdout: [I 201015 02:00:23 worker:51] 2 task done. 0 success, 2 failed
stdout: [E 201015 06:00:34 worker:274] taskid:3 tplid:3 failed! Exception(u"failed at 1/11 request, error:error(111, 'Connection refused'), https://api.smzdm.com/v1/user/checkin",) 0.8373s
stderr: [E 201015 06:00:34 worker:274] taskid:3 tplid:3 failed! Exception(u"failed at 1/11 request, error:error(111, 'Connection refused'), https://api.smzdm.com/v1/user/checkin",) 0.8373s
stdout: [E 201015 06:00:34 worker:274] taskid:2 tplid:2 failed! Exception(u"failed at 1/1 request, error:error(111, 'Connection refused'), https://www.right.com.cn/forum/forum.php",) 1.7470s
stderr: [E 201015 06:00:34 worker:274] taskid:2 tplid:2 failed! Exception(u"failed at 1/1 request, error:error(111, 'Connection refused'), https://www.right.com.cn/forum/forum.php",) 1.7470s
stdout: [I 201015 06:00:34 worker:51] 2 task done. 0 success, 2 failed
stderr: [E 201015 12:00:42 worker:274] taskid:3 tplid:3 failed! Exception(u"failed at 1/11 request, error:error(111, 'Connection refused'), https://api.smzdm.com/v1/user/checkin",) 0.1971s
stdout: [E 201015 12:00:42 worker:274] taskid:3 tplid:3 failed! Exception(u"failed at 1/11 request, error:error(111, 'Connection refused'), https://api.smzdm.com/v1/user/checkin",) 0.1971s
stdout: [E 201015 12:00:42 worker:274] taskid:2 tplid:2 failed! Exception(u"failed at 1/1 request, error:error(111, 'Connection refused'), https://www.right.com.cn/forum/forum.php",) 0.4883s
stderr: [E 201015 12:00:42 worker:274] taskid:2 tplid:2 failed! Exception(u"failed at 1/1 request, error:error(111, 'Connection refused'), https://www.right.com.cn/forum/forum.php",) 0.4883s
stdout: [I 201015 12:00:42 worker:51] 2 task done. 0 success, 2 failed
stdout: [I 201015 17:23:13 web:2064] 302 GET / (172.31.0.1) 30.47ms
stdout: [I 201015 17:23:14 web:2064] 200 GET /my/ (172.31.0.1) 72.03ms
stdout: [I 201015 17:23:15 web:2064] 304 GET /static/body.jpg (172.31.0.1) 4.60ms
stdout: [I 201015 17:23:15 web:2064] 304 GET /static/header.jpg (172.31.0.1) 3.94ms
stdout: [I 201015 17:23:15 web:2064] 304 GET /static/components/bootstrap/dist/fonts/glyphicons-halflings-regular.woff (172.31.0.1) 4.20ms
stdout: [I 201015 17:23:16 web:2064] 200 GET /static/img/icon.png?v=805c611920555b870651cd98c6f93777 (172.31.0.1) 6.35ms
stdout: [I 201015 17:23:46 web:2064] 200 GET /subscribe/ (172.31.0.1) 116.46ms
stdout: [W 201015 17:23:47 web:2064] 404 GET /favicon.ico (172.31.0.1) 11.88ms
stderr: [W 201015 17:23:47 web:2064] 404 GET /favicon.ico (172.31.0.1) 11.88ms
stdout: [I 201015 17:30:46 web:2064] 200 GET /subscribe/ (172.31.0.1) 84.89ms
stdout: [I 201015 17:33:00 web:2064] 304 GET /my/ (172.31.0.1) 34.83ms
stdout: [I 201015 17:36:18 web:2064] 302 GET / (172.31.0.1) 5.87ms
stdout: [I 201015 17:36:18 web:2064] 304 GET /my/ (172.31.0.1) 39.49ms
stdout: [I 201015 17:36:22 web:2064] 200 POST /task/3/run (172.31.0.1) 192.42ms
stdout: [I 201015 17:36:25 web:2064] 200 POST /task/2/run (172.31.0.1) 203.14ms
stdout: [I 201015 17:36:28 web:2064] 200 GET /subscribe/ (172.31.0.1) 79.88ms
stdout: [I 201015 17:38:12 web:2064] 200 GET /subscribe/ (172.31.0.1) 99.58ms

**Comment by ZHOU202** [comment]
![QQ截图20201015174301](https://user-images.githubusercontent.com/40857974/96106514-e53e7800-0f0d-11eb-864a-2aa9ee237221.jpg)
大佬，这是我的容器设置

**Comment by AragonSnow** [comment]
@ZHOU202 
1.访问码云失败，所以打不开。你是在国外？
2.connection refused, 网络问题，查看防火墙等是否放行你的docker 访问网络。

**Comment by ZHOU202** [comment]
> @ZHOU202
> 1.访问码云失败，所以打不开。你是在国外？
> 2.connection refused, 网络问题，查看防火墙等是否放行你的docker 访问网络。

**Comment by ZHOU202** [comment]
> @ZHOU202
> 1.访问码云失败，所以打不开。你是在国外？
> 2.connection refused, 网络问题，查看防火墙等是否放行你的docker 访问网络。

1.大佬，我在国内，在国内不能访问公共模板，只要ssr打开全局代理才能访问，一些har文件也需要全局代理才能访问
2.请问防火墙怎么放行docker访问网络

**Comment by ZHOU202** [comment]
@AragonSnow

**Comment by ZHOU202** [comment]
@AragonSnow 
![QQ截图20201018162026](https://user-images.githubusercontent.com/40857974/96362162-f8478700-115d-11eb-8ecc-6cc13ab18064.jpg)
![QQ截图20201018162051](https://user-images.githubusercontent.com/40857974/96362169-fe3d6800-115d-11eb-8575-d678cbfe727d.jpg)

**Comment by ZHOU202** [comment]
麻烦大佬帮我看看，好多人和我一样的情况，不知道什么情况

**Comment by ZHOU202** [comment]
![Uploading QQ截图20201018162521.jpg…]()

**Comment by ZHOU202** [comment]
![Uploading QQ截图20201018162521.jpg…]()

**Comment by ZHOU202** [comment]
docker 内网络正常，但是容器里没有网络

**Comment by Fofade** [comment]
> docker 内网络正常，但是容器里没有网络

把设备防火墙关了。再不行就买台国内的服务器部署，你这些问题就都能解决。

**Comment by AragonSnow** [comment]
在路由上运行的docker启动方法：
···
docker run -d --name qiandao --network=host --env PORT=12345 -v $(pwd)/qiandao/config:/usr/src/app/config asdaragon/qiandao
···
然后访问12345端口
